-- InBridge database schema — generated from db/migrations/*.sql
-- Apply once to a fresh Postgres (Supabase SQL editor, or: cd backend && go run ./cmd/dbinit)

-- ── 001_citizens.sql ──────────────────────────────────────────────
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

CREATE TABLE IF NOT EXISTS citizens (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    vid VARCHAR(255) UNIQUE NOT NULL, -- Never raw Aadhaar, only VID
    full_name VARCHAR(255) NOT NULL,
    email VARCHAR(255) UNIQUE NOT NULL,
    password_hash VARCHAR(255) NOT NULL,
    date_of_birth VARCHAR(20) NOT NULL,
    gender VARCHAR(10) NOT NULL,
    state VARCHAR(100) NOT NULL,
    district VARCHAR(100) NOT NULL,
    mobile_number VARCHAR(15),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_citizens_vid ON citizens(vid);

-- ── 002_applications.sql ──────────────────────────────────────────────
-- Requires UUID v7 for sequential indexing, generated by Go
CREATE TABLE IF NOT EXISTS applications (
    id UUID PRIMARY KEY,
    citizen_id UUID NOT NULL REFERENCES citizens(id) ON DELETE RESTRICT,
    arn VARCHAR(100) UNIQUE NOT NULL, -- Application Reference Number
    service_code VARCHAR(50) NOT NULL,
    status VARCHAR(50) NOT NULL DEFAULT 'SUBMITTED',
    form_data JSONB NOT NULL DEFAULT '{}',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_applications_citizen_id ON applications(citizen_id);
CREATE INDEX idx_applications_arn ON applications(arn);

-- ── 003_audit_log.sql ──────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS audit_log (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    citizen_id UUID NOT NULL REFERENCES citizens(id) ON DELETE RESTRICT,
    action VARCHAR(255) NOT NULL,
    resource VARCHAR(255) NOT NULL,
    ip_address INET,
    user_agent TEXT,
    timestamp_ist TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT (CURRENT_TIMESTAMP AT TIME ZONE 'Asia/Kolkata')
);

CREATE INDEX idx_audit_log_citizen_id ON audit_log(citizen_id);
CREATE INDEX idx_audit_log_timestamp ON audit_log(timestamp_ist);

-- Append-only constraint via DB permissions (assuming app connects as specific user)
-- Alternatively, we can use a trigger to prevent updates and deletes
CREATE OR REPLACE FUNCTION prevent_audit_modifications()
RETURNS TRIGGER AS $$
BEGIN
    RAISE EXCEPTION 'Updates and deletes are not allowed on the audit_log table. CERT-In compliance requirement.';
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER audit_log_prevent_modifications
BEFORE UPDATE OR DELETE ON audit_log
FOR EACH ROW
EXECUTE FUNCTION prevent_audit_modifications();

-- ── 005_ai_chat.sql ──────────────────────────────────────────────
-- Step 1: Create Conversations table
CREATE TABLE conversations (
    id            UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    citizen_id    UUID NOT NULL, -- references citizens(id) once auth is fixed, omitting FK for standalone demo ease
    title         TEXT,
    provider      TEXT NOT NULL,
    model         TEXT NOT NULL,
    created_at    TIMESTAMPTZ DEFAULT now(),
    updated_at    TIMESTAMPTZ DEFAULT now()
);

-- Step 2: Create Messages table
CREATE TABLE messages (
    id              UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    conversation_id UUID NOT NULL REFERENCES conversations(id) ON DELETE CASCADE,
    role            TEXT NOT NULL CHECK (role IN ('user', 'assistant')),
    content         TEXT NOT NULL,
    tokens_used     INTEGER,
    created_at      TIMESTAMPTZ DEFAULT now()
);

-- Step 5: Create Indexes for Performance
CREATE INDEX idx_conversations_citizen ON conversations(citizen_id, updated_at DESC);
CREATE INDEX idx_messages_conversation ON messages(conversation_id, created_at ASC);

-- ── 006_grievances.sql ──────────────────────────────────────────────
-- 006_grievances.sql
CREATE TABLE IF NOT EXISTS grievances (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    citizen_id UUID NOT NULL REFERENCES citizens(id) ON DELETE CASCADE,
    subject VARCHAR(200) NOT NULL,
    description TEXT NOT NULL,
    status VARCHAR(50) NOT NULL DEFAULT 'REGISTERED',
    resolution TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_grievances_citizen_id ON grievances(citizen_id);
CREATE INDEX idx_grievances_status ON grievances(status);

-- ── 007_performance_indexes.sql ──────────────────────────────────────────────
-- ============================================================
-- Migration 007: Performance indexes for grievances, audit_log,
--                and optimised pool config comments.
-- ============================================================
-- Context: Load testing revealed:
--   1. GET /api/v1/grievance/:id does a PK lookup — already fast.
--   2. Any future "list grievances by citizen" query would do a seq-scan
--      on grievances(citizen_id) without this index.
--   3. audit_log has no index on (citizen_id, timestamp_ist) — slow
--      for compliance queries filtering by citizen over time ranges.
--
-- NOTE: CREATE INDEX CONCURRENTLY is used so this migration does not
--       lock the tables in production. Run outside a transaction block.
-- ============================================================

-- Grievances: citizen lookup + status filtering
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_grievances_citizen_id
    ON grievances(citizen_id);

CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_grievances_citizen_status
    ON grievances(citizen_id, status);

-- Audit log: compliance and alerting range queries
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_audit_log_citizen_time
    ON audit_log(citizen_id, timestamp_ist DESC);

CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_audit_log_action
    ON audit_log(action, timestamp_ist DESC);

-- Applications: service_code filtering (for admin dashboards)
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_applications_service_status
    ON applications(service_code, status);

