-- Requires UUID v7 for sequential indexing, generated by Go
CREATE TABLE IF NOT EXISTS applications (
    id UUID PRIMARY KEY,
    citizen_id UUID NOT NULL REFERENCES citizens(id) ON DELETE RESTRICT,
    arn VARCHAR(100) UNIQUE NOT NULL, -- Application Reference Number
    service_code VARCHAR(50) NOT NULL,
    status VARCHAR(50) NOT NULL DEFAULT 'SUBMITTED',
    form_data JSONB NOT NULL DEFAULT '{}',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_applications_citizen_id ON applications(citizen_id);
CREATE INDEX idx_applications_arn ON applications(arn);
